/**
 * CSS colors array
 */
export const GLOW_COLORS = [
  '#a80000',
  '#c50000',
  '#e20000',
  '#ff0000',
  '#a81f00',
  '#c52500',
  '#e22a00',
  '#ff3000',
  '#a83f00',
  '#c54a00',
  '#e25500',
  '#ff6000',
  '#a85e00',
  '#c56f00',
  '#e27f00',
  '#ff8f00',
  '#a87e00',
  '#c59400',
  '#e2a900',
  '#ffbf00',
  '#a89d00',
  '#c5b800',
  '#e2d400',
  '#ffef00',
  '#93a800',
  '#acc500',
  '#c6e200',
  '#dfff00',
  '#73a800',
  '#87c500',
  '#9be200',
  '#afff00',
  '#54a800',
  '#62c500',
  '#71e200',
  '#7fff00',
  '#34a800',
  '#3dc500',
  '#47e200',
  '#50ff00',
  '#15a800',
  '#19c500',
  '#1ce200',
  '#20ff00',
  '#00a80a',
  '#00c50c',
  '#00e20e',
  '#00ff10',
  '#00a82a',
  '#00c531',
  '#00e238',
  '#00ff40',
  '#00a849',
  '#00c556',
  '#00e263',
  '#00ff70',
  '#00a869',
  '#00c57b',
  '#00e28d',
  '#00ff9f',
  '#00a888',
  '#00c5a0',
  '#00e2b8',
  '#00ffcf',
  '#00a8a8',
  '#00c5c5',
  '#00e2e2',
  '#00ffff',
  '#0088a8',
  '#00a0c5',
  '#00b8e2',
  '#00cfff',
  '#0069a8',
  '#007bc5',
  '#008de2',
  '#009fff',
  '#0049a8',
  '#0056c5',
  '#0063e2',
  '#0070ff',
  '#002aa8',
  '#0031c5',
  '#0038e2',
  '#0040ff',
  '#000aa8',
  '#000cc5',
  '#000ee2',
  '#0010ff',
  '#1500a8',
  '#1900c5',
  '#1c00e2',
  '#2000ff',
  '#3400a8',
  '#3d00c5',
  '#4700e2',
  // * purple-pink
  '#5000ff',
  '#5400a8',
  '#6200c5',
  '#7100e2',
  '#7f00ff',
  '#7300a8',
  '#8700c5',
  '#9b00e2',
  '#af00ff',
  '#9300a8',
  '#ac00c5',
  '#c600e2',
  '#5000ff',
  '#5400a8',
  '#6200c5',
  '#7100e2',
  '#7f00ff',
  '#7300a8',
  '#8700c5',
  '#9b00e2',
  '#af00ff',
  '#9300a8',
  '#ac00c5',
  '#c600e2',
  '#5000ff',
  '#5400a8',
  '#6200c5',
  '#7100e2',
  '#7f00ff',
  '#7300a8',
  '#8700c5',
  '#9b00e2',
  '#af00ff',
  '#9300a8',
  '#ac00c5',
  '#c600e2',
  // * purple-pink-end
  '#df00ff',
  '#a8009d',
  '#c500b8',
  '#e200d4',
  '#ff00ef',
  '#a8007e',
  '#c50094',
  '#e200a9',
  '#ff00bf',
  '#a8005e',
  '#c5006f',
  '#e2007f',
  '#ff008f',
  '#a8003f',
  '#c5004a',
  '#e20055',
  '#ff0060',
  '#a8001f',
  '#c50025',
  '#e2002a',
  '#ff0030',
];

export const THEME_COLOR_IDS = [
  // Base
  'focusBorder',
  'foreground',
  'disabledForeground',
  'errorForeground',
  'icon.foreground',
  'selection.background',
  'widget.border',
  'widget.shadow',

  // Activity Bar
  'activityBar.background',
  'activityBar.foreground',
  'activityBar.inactiveForeground',
  'activityBar.border',
  'activityBar.activeBorder',
  'activityBar.activeFocusBorder',
  'activityBarBadge.background',
  'activityBarBadge.foreground',

  // Editor Core
  'editor.background',
  'editor.foreground',
  'editorCursor.foreground',
  'editorCursor.background',
  'editor.selectionBackground',
  'editor.selectionForeground',
  'editor.inactiveSelectionBackground',
  'editor.lineHighlightBackground',
  'editor.lineHighlightBorder',
  'editor.findMatchBackground',
  'editor.findMatchHighlightBackground',
  'editor.wordHighlightBackground',
  'editor.wordHighlightStrongBackground',
  'editor.hoverHighlightBackground',
  'editor.rangeHighlightBackground',
  'editor.symbolHighlightBackground',
  'editor.foldBackground',
  'editor.foldPlaceholderForeground',

  // Editor Gutter / Line Numbers
  'editorLineNumber.foreground',
  'editorLineNumber.activeForeground',
  'editorGutter.background',
  'editorGutter.modifiedBackground',
  'editorGutter.addedBackground',
  'editorGutter.deletedBackground',

  // Editor Whitespace / Guides
  'editorWhitespace.foreground',
  'editorIndentGuide.background',
  'editorIndentGuide.activeBackground',
  'editorRuler.foreground',

  // Tabs / Editor Groups
  'editorGroup.border',
  'editorGroupHeader.tabsBackground',
  'editorGroupHeader.tabsBorder',
  'editorGroupHeader.border',
  'tab.activeBackground',
  'tab.inactiveBackground',
  'tab.activeForeground',
  'tab.inactiveForeground',
  'tab.border',
  'tab.unfocusedActiveBackground',
  'tab.unfocusedInactiveBackground',

  // Sidebar
  'sideBar.background',
  'sideBar.foreground',
  'sideBar.border',
  'sideBarTitle.foreground',
  'sideBarSectionHeader.background',
  'sideBarSectionHeader.foreground',

  // Status Bar
  'statusBar.background',
  'statusBar.foreground',
  'statusBar.border',
  'statusBar.debuggingBackground',
  'statusBar.noFolderBackground',
  'statusBarItem.hoverBackground',
  'statusBarItem.activeBackground',
  'statusBarItem.prominentBackground',

  // Title Bar
  'titleBar.activeBackground',
  'titleBar.activeForeground',
  'titleBar.inactiveBackground',
  'titleBar.inactiveForeground',
  'titleBar.border',

  // Panels
  'panel.background',
  'panel.border',
  'panelTitle.activeForeground',
  'panelTitle.inactiveForeground',

  // Buttons / Inputs
  'button.background',
  'button.foreground',
  'button.hoverBackground',
  'input.background',
  'input.foreground',
  'input.border',
  'input.placeholderForeground',
  'dropdown.background',
  'dropdown.foreground',
  'dropdown.border',

  // Lists / Trees
  'list.activeSelectionBackground',
  'list.activeSelectionForeground',
  'list.inactiveSelectionBackground',
  'list.inactiveSelectionForeground',
  'list.hoverBackground',
  'list.focusBackground',
  'list.errorForeground',
  'list.warningForeground',

  // Notifications
  'notifications.background',
  'notifications.foreground',
  'notifications.border',
  'notificationCenterHeader.background',
  'notificationToast.border',
  'notificationsErrorIcon.foreground',
  'notificationsWarningIcon.foreground',
  'notificationsInfoIcon.foreground',

  // Terminal
  'terminal.background',
  'terminal.foreground',
  'terminalCursor.foreground',
  'terminal.ansiBlack',
  'terminal.ansiRed',
  'terminal.ansiGreen',
  'terminal.ansiYellow',
  'terminal.ansiBlue',
  'terminal.ansiMagenta',
  'terminal.ansiCyan',
  'terminal.ansiWhite',
  'terminal.ansiBrightBlack',
  'terminal.ansiBrightRed',
  'terminal.ansiBrightGreen',
  'terminal.ansiBrightYellow',
  'terminal.ansiBrightBlue',
  'terminal.ansiBrightMagenta',
  'terminal.ansiBrightCyan',
  'terminal.ansiBrightWhite',

  // Peek / Diff
  'peekView.border',
  'peekViewEditor.background',
  'peekViewResult.background',
  'diffEditor.insertedTextBackground',
  'diffEditor.removedTextBackground',

  // Debug
  'debugIcon.breakpointForeground',
  'debugIcon.breakpointDisabledForeground',
  'debugConsole.errorForeground',
  'debugConsole.warningForeground',
  'debugConsole.infoForeground',

  // SCM / Git
  'gitDecoration.addedResourceForeground',
  'gitDecoration.modifiedResourceForeground',
  'gitDecoration.deletedResourceForeground',
  'gitDecoration.untrackedResourceForeground',
  'gitDecoration.ignoredResourceForeground',

  // Charts / Extensions
  'charts.red',
  'charts.blue',
  'charts.green',
  'charts.orange',
  'extensionButton.prominentBackground',
  'extensionButton.prominentForeground',
];
